<?php
/**
 * Student Summary Report Function.
 */
function reports() { 
 return '<div class="admin-panel">
              <h3>Reports</h3>
              <ul class="admin-list compact">
              <li><a href="reports/summary/studentreports">Student Summary Reports</a></li>
              <li><a href="reports/detail/studentreports">Student Detail Reports</a></li>
              <li><a href="reports/summary/employerreports">Employer Summary Reports</a></li>
              <li><a href="reports/detail/employerreports">Employer Detail Reports</a></li>
              <li><a href="reports/summary/jobreports">Job Summary Reports</a></li>
              <li><a href="reports/detail/jobreports">Job Detail Reports</a></li>
              </ul></div>';

}

